domain: hanoi.seiichiyonezawa.com
url: https://hanoi.seiichiyonezawa.com
exclude:
  - package.json
  - package-lock.json
  - CNAME
  - README.md
  - playwright.config.js
  - Gemfile
  - Gemfile.lock
  - tests
  - node_modules
